### ISSUE TITLE
Update screenshots/html.png

### ISSUE THREAD

**Issue by sbruchmann** [Brackets-Themes/Monokai#7]
ed3a112 changed the syntax highlighting for markup languages, thus `screenshots/html.png` needs to be updated. Assigning to self. Won’t be mad if anybody else want to do this, though. ;)

**Comment by MarcelGerber** [comment]
You should've updated all the screenshots in a row. The old ones still have the light status bar and are missing the Split View button.

**Comment by sbruchmann** [comment]
@MarcelGerber Done via 2994b81.
