### ISSUE TITLE
Theme doesent work, then Breaks 'Brackets Git' extension then wont uninstall

### ISSUE THREAD

**Issue by 9000-volts** [Brackets-Themes/Monokai#9]
After installing this extension, upon starting brackets I receive a notification from another extension (brackets git) saying it failed to connect to nodejs.
Also, it does not apply at all, i see no change to brackets.
Upon attempting to remove this extension, i get a message saying "Unable to remove one or more extensions: monokai-theme. Brackets will still reload".

**Comment by wormeyman** [comment]
I'm having the same problem with Brackets Git as well, i do not think it is Monokai though.

**Comment by 9000-volts** [comment]
Update: After Restarting the system, Monokai still did not appear, but Removed Correctly. Brackets-Git no longer gives the error, which seems to have been somehow caused by installing Monokai theme.

**Comment by MiguelCastillo** [comment]
@htmlguy is this issue logged with brackets?

/cc @zaggino

**Comment by zaggino** [comment]
Just tested, I have absolutely no issues running this theme together with Brackets-Git and I doubt that any theme would break node-connection. Try getting out the logs from your console (f12) and submitting an issue with Brackets-Git if you can find anything useful in there.

**Comment by MiguelCastillo** [comment]
@zaggino I really didn't think that they wouldn't mix... I am not even sure why this is even possible.

@htmlguy what other extensions do you installed?

**Comment by zaggino** [comment]
@htmlguy you can use

```
bracketsGit.getInstalledExtensions()
```

in the console when Brackets-Git is installed, you'll get also a list of extensions which are using connection to Node in Brackets.

**Comment by 9000-volts** [comment]
I was using:
- "Brackets Extension - UTF8 converter"
- "Brackets Git"
- "Install from Bower"
  Also: The issue is not logged with brackets AFAIK

**Comment by MiguelCastillo** [comment]
@htmlguy  What version of brackets are you running?

**Comment by 9000-volts** [comment]
I am using latest version: 1.1 (W/O extract)
